In [5]:
import pandas as pd

In [9]:
data_orig = pd.read_csv('data/preprocessed_data.csv') # missing values + other problems + one hot encoding

data_eng = pd.read_csv('data/preprocessed_data_engineered.csv') # preprocessed + engineered features
data_sel = pd.read_csv('data/preprocessed_data_feat_selection.csv') # preprocessed + engineered features + feature selection

# TODO: data PCA

# TODO: vale a pena ter data_eng e data_sel ?? era preferível ter só data_sel que já inclui engineering

datasets = [data_orig, data_eng, data_sel]

for dataset in datasets:
    dataset.set_index('PUF_ID', inplace=True)

# Original data after preprocessing

In [10]:
data_orig.head()

,fpl,SWB_1,SWB_2,SWB_3,FWBscore,FSscore,SUBKNOWL1,ACT1_1,ACT1_2,PROPPLAN_1,...,PPREG4_3,PPREG4_4,PPREG9_2,PPREG9_3,PPREG9_4,PPREG9_5,PPREG9_6,PPREG9_7,PPREG9_8,PPREG9_9
PUF_ID,,,,,,,,,,,,,,,,,,,,,
10350,3,5.0,5.0,6.0,55.0,44.0,5.0,4.0,3.0,5.0,...,0,1,0,0,0,0,0,0,1,0
7740,3,6.0,6.0,6.0,51.0,43.0,5.0,4.0,3.0,3.0,...,0,0,0,1,0,0,0,0,0,0
13699,3,4.0,3.0,4.0,49.0,42.0,5.0,3.0,3.0,4.0,...,0,1,0,0,0,0,0,0,0,1
7375,3,4.0,4.0,4.0,49.0,42.0,4.0,3.0,3.0,3.0,...,0,0,0,0,1,0,0,0,0,0
10910,3,5.0,7.0,5.0,67.0,57.0,6.0,5.0,4.0,5.0,...,0,0,0,1,0,0,0,0,0,0

In [40]:
num_feats = list(filter(lambda x: data_orig[x].nunique() > 2, data_orig.columns.values))
cat_feats = list(filter(lambda x: data_orig[x].nunique() == 2, data_orig.columns.values))

print('Numerical features: ', len(num_feats) - 2) # remove fpl and finalwt
print('One hot features: ', len(cat_feats))

Numerical features:  63
One hot features:  127

# Feature Engineering + Feature Selection Data

In [42]:
data_sel.head()

,fpl,FWBscore,FSscore,SUBKNOWL1,SAVEHABIT,FRUGALITY,ASK1_1,ASK1_2,SUBNUMERACY2,SUBNUMERACY1,...,PPREG4_3,PPREG4_4,PPREG9_2,PPREG9_3,PPREG9_4,PPREG9_5,PPREG9_6,PPREG9_7,PPREG9_8,PPREG9_9
PUF_ID,,,,,,,,,,,,,,,,,,,,,
10350,3,55.0,44.0,5.0,4.0,6.0,4.0,3.0,3.0,3.0,...,0,1,0,0,0,0,0,0,1,0
7740,3,51.0,43.0,5.0,1.0,5.0,3.0,2.0,5.0,5.0,...,0,0,0,1,0,0,0,0,0,0
13699,3,49.0,42.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,...,0,1,0,0,0,0,0,0,0,1
7375,3,49.0,42.0,4.0,4.0,4.0,3.0,3.0,4.0,4.0,...,0,0,0,0,1,0,0,0,0,0
10910,3,67.0,57.0,6.0,4.0,5.0,5.0,3.0,5.0,6.0,...,0,0,0,1,0,0,0,0,0,0

In [43]:
num_feats = list(filter(lambda x: data_sel[x].nunique() > 2, data_sel.columns.values))
cat_feats = list(filter(lambda x: data_sel[x].nunique() == 2, data_sel.columns.values))

print('Numerical features: ', len(num_feats) - 2) # remove fpl and finalwt
print('Categorical features: ', len(cat_feats))

Numerical features:  42
Categorical features:  120